### ISSUE TITLE
Books covers from Amazon

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-books#14]
It looks like that to be able to use Amazon covers we need to comply with Amazon TOS, which in a few points (to be reviewed!) means:
* cannot download images
* cannot cache images
* cannot manipulate the URL
* can cache/save the URL to an image for max 24 hours
* we can store the ASIN (Amazon identifier) which is useful to fetch the book with Amazon API

Reference: (check point VIII):
FR: https://partenaires.amazon.fr/help/operating/license
IT: https://programma-affiliazione.amazon.it/help/operating/license
Same page in `.com` is blank: https://affiliate-program.amazon.com/help/operating/license but reading around, it has the same policy.

**How fetching works now in CDS**
1. Search using API by ISBN: `http://webservices.amazon.fr/onca/xml?SearchIndex=Books&Power=ISBN%3A9780486688954...`
2. Normally there is only 1 results, parse it and fetch the images urls

[Amazon API documentation](https://docs.aws.amazon.com/AWSECommerceService/latest/DG/Welcome.html)

**Extra**

It might be wise to create a dedicated microservice for this.

A tool to fetch book cover from multiple sources (as inspiration):
https://github.com/fredericd/coce

**Comment by agentilb** [comment]
In addition to this, here is the list of all Operating agreements for the different Amazons:
https://docs.aws.amazon.com/AWSECommerceService/latest/DG/AmazonsLicensingAgreement.html

For .fr, .it and .de this links to a specific license about the API as said above, whereas for .com and .uk, this links to a general agreement about the associate program, which then links to this document, I did not notice before: <https://affiliate-program.amazon.com/help/operating/policies/>

Here we find basically the same instruction as for .fr, .it and .de:

(h) You will not store or cache Product Advertising Content consisting of an image, but you may store a link to Product Advertising Content consisting of an image for up to 24 hours. You may store other Product Advertising Content that does not consist of images for caching purposes for up to 24 hours, but if you do so you must immediately thereafter refresh and re-display the Product Advertising Content by making a call to PA API or retrieving a new Data Feed and refreshing the Product Advertising Content on your application immediately thereafter. Unless otherwise notified by us, you may store individual Amazon Standard Identification Numbers (ASINs) for an indefinite period until the termination of this License. Notwithstanding the foregoing, if your application includes a client application, the client application may not store or cache Product Advertising Content. Upon our request you will, within three business days of our request, furnish us with a copy of any client application that includes or uses Product Advertising Content for the purpose of verifying your compliance with this License.

**Comment by ntarocco** [comment]
Book cover provider changed.
